### PR TITLE
Repository Reorganization

### LINKED ISSUE #611: Combine Network, Node, and Worker to create a monorepo
We want to have a PyGrid reorganization [similar to this](https://medium.com/opendoor-labs/our-python-monorepo-d34028f2b6fa) so that we can do the following:

- Manage all of our dependencies in one place, and be able to set global dependency versions so that we don't have conflicting versions of the same package running in our various components
- Be able to test across our components (end-to-end testing)
- Be able to write infrastructure code across our components (infrastructure as code)
- Have a single repository to document
- Have a single repository to test
- Have a single place to gather issues about the various components in the system

### PR DESCRIPTION
**Pull request by IonesioJunior**
## Description
Due to the need to add CI integration tests between different PyGrid components, we're reorganizing our repository to accomplish #611 requirements.

Fix #611 

## Checklist
- [x] Create a proper path structure to network/node/worker apps
   - [x] Move PyGridNode App to PyGrid
   - [x] Move GridNetwork to PyGrid
   - [x] Create GridWorker
- [x] Split tests into unit tests/integration tests
   - [x] Update tests references
   - [x] Split current tests between events/routes/database
   - [x] Update github actions configs
- [x] Manage dependencies
  - [x] Manage dependencies using poetry
  - [x] Update github actions 
- [x] Remove outdated config files
- [x] Update release settings
- [ ] Update Dockerfile references
- [X] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have commented on my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [X] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by IonesioJunior** [comment]
This is what the repository architecture should look like after this PR.

Untitled Diagram (8)

**Comment by IonesioJunior** [comment]
Comments/thoughts will be very appreciated! :)

**Comment by jmaunon** [comment]
LGTM! Some comments:

- Pygrid/apps/node/requirements.txt can be removed (dependencies managed by poetry)
- I would create new issues/PR for the following:
  - Update Dockerfiles 
  - Update Readme of the repository

**Comment by cereallarceny** [comment]
@IonesioJunior should we wait on docker or merge this before then?

**Comment by Benardi** [comment]
Looks like org scoping and poetry do not go along: 

image

**Comment by cereallarceny** [comment]
Do you mind taking care of these things @Benardi ?

**Comment by Benardi** [comment]
Executing the tests locally for app `node` led to an error :

image

**Comment by AmrMKayid** [comment]
What is the difference between `apps/node/src/__main__.py` and `apps/node/src/grid.py` as I see both files are identical to each others .. do we need `apps/node/src/grid.py` or we should remove it?

**Comment by jmaunon** [comment]
> What is the difference between `apps/node/src/__main__.py` and `apps/node/src/grid.py` as I see both files are identical to each others .. do we need `apps/node/src/grid.py` or we should remove it?

Yep. They are the same. I see @cereallarceny  has deleted it

**Pull request merged**
