### PR TITLE
setup configuration

### LINKED ISSUE #542: Semantic versioning
**Is your feature request related to a problem? Please describe.**
The protect should keep a semantic versioning [](https://semver.org/)

**Describe the solution you'd like**
I would recommend a `setup.py` like Pysyft

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by jmaunon**
# Setup configuration

## Description

It is is recommended to have a setup.py for proper version of the development.
It is related with #542 

Fixes #542 

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
The existing tests should run in the same way.
The setup.py should generate a package.

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [x] Unit tests pass locally with my changes

## Progress:
I have followed the same guidelines from PySyft repository
- [x] File setup.py with description
- [x] Update of:
  - [x] tests. Now the tests uses grid package `import grid.app`
  - [x] Github actions. New line running `python setup.py install`
  - [x] Makefile. Update of make venv and make test in order to catch all requirements and run the test using coverage
- [x] Update documentation about how to install and run

### CODE REVIEW

**Comment by jmaunon** [comment]
Hi @IonesioJunior 
I have created the setup.py and updated the folder structure (this impacts on tests, github actions and so on).
It is necessary to update the documentation, but before doing this I wanted to feedback about this PR.
Is it ok for you or is something missing? (apart of documentation)
Thanks

**Comment by IonesioJunior** [comment]
Hello @jmaunon!
Yep, sounds good to me! :)
We just need to solve this merge conflicts.

But you're doing an awesome job! :)

**Comment by Benardi** [comment]
The build is not being triggered.
This might have something to do with your changes (I've been though something similar before).

**Comment by jmaunon** [comment]
Hi @Benardi. Thanks for your comment
I do not fully know why.
I have modified the GitHub actions in my branch in order to consider the new folder structure. Is related with this?

I do not know if is trigger for the action in the source branch or in the target.

**Comment by Benardi** [comment]
> I

I'm puzzled as well, maybe solving the conflicts will shed some light.

**Comment by Benardi** [comment]
I've made some tests inside a fork of your fork, and once the conflicts are solved the build starts once again:

https://github.com/Benardi/PyGrid/pull/4

**Comment by jmaunon** [comment]
Hi @IonesioJunior 
From my point of view,  this PR is ready for merge

In this way, PyGrid is easier to distribute and version. After this PR, if you agree, I can do the same with GridNode.

In addition, I would suggest to create a protected master branch, for future releases.

**Comment by IonesioJunior** [comment]
Hello @jmaunon, well done!
But we still have merge conflicts at `app/main/controller/fl_controller.py`, `app/main/models/model_manager.py`, and `requirements.txt`.
Could you check it, please? :)
`

**Comment by jmaunon** [comment]
> Hello @jmaunon, well done!
> But we still have merge conflicts at `app/main/controller/fl_controller.py`, `app/main/models/model_manager.py`, and `requirements.txt`.
> Could you check it, please? :)
> `

Hi @Ionesio. I have check again (just in case) the conflicting files and they are ok (I pass the tests locally)

I think the conflicts come from previous commits. Actually, those file do not exist in that path, now are moved to _grid/app/main/..._

**Comment by IonesioJunior** [comment]
Oh, yeah! It makes total sense!
Reviewing it right now! ;)

**Comment by jmaunon** [comment]
Hi @Benardi .
Thanks a lot for your comment.

Can you help me with rebase? As you say is very tricky and what I do not like is what I have know, a lot of commits non related with my work.

**Comment by Benardi** [comment]
> Hi @Benardi .
> Thanks a lot for your comment.
> 
> Can you help me with rebase? As you say is very tricky and what I do not like is what I have know, a lot of commits non related with my work.
> 
> Actually there is something that I am not understanding because I see that in my branch everything is ok, but it isn't because you have a screenshot with conflicts...

Are you in the Openmined's Slack ? You can find me over there as **Benardi Nunes**

I've seen the situation of the branch history and I think that in the case of this PR it would enough to solve the conflicts, because It would take too much effort to set this branch history right. We could do this together via Slack / Hangouts / Google Meet.

**Comment by Benardi** [comment]
The `dev` branch in your repository is `242 commits ahead, 2 commits behind OpenMined:dev` that's probably why you can't see the conflicts.

**Comment by jmaunon** [comment]
Thanks @Benardi, I will contact you via slack.
Thanks a lot!

**Comment by jmaunon** [comment]
Ey, I think that now everything is ok. Thanks a lot @Benardi and @IonesioJunior  for your help!

**Pull request merged**
