### PR TITLE
Update Rest API for websocket

### LINKED ISSUE #393: Update the websocket API
**Describe the bug**
The websocket API is outdated.

**Expected behavior**
The ```grid_node_websocket_api.rst``` should contain the correct functions.

### PR DESCRIPTION
**Pull request by gmuraru**
## Description

Update the REST Api file for the Websocket app

Fixes #393 

## Type of change

- [x] Documentation update

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [x] New Unit tests added - Not needed
- [x] Unit tests pass locally with my changes

## Tested manually
1. Started websocket grid node using the following command
```python websocket_app.py --start_local_db --id=bob --port=3000
python websocket_app.py --start_local_db --id=anne --port=3001
python websocket_app.py --start_local_db --id=james --port=3002
```

2. Upload 1 simple model (only a Linear layer) with 2 names
```
import torch as th
import syft as sy
import grid as gr
import torch.nn.functional as F

hook = sy.TorchHook(th)

# Connect to the grid nodes
bob = gr.WebsocketGridClient(hook, "http://localhost:3000", id="bob")
anne = gr.WebsocketGridClient(hook, "http://localhost:3001", id="anne")
james = gr.WebsocketGridClient(hook, "http://localhost:3002", id="james")

# Upload downloadable and not downloadable models to worker anne
model = th.nn.Linear(1, 1)
traced_model = th.jit.trace(model, th.Tensor([1.0]))

anne.serve_model(traced_model, "trace_model5", allow_download=False)
anne.serve_model(traced_model, "trace_model3", allow_download=True)


#### THIS PART DID NOT WORK
# Define a new model - it needs to have the encrypt attribute - it's the one from the skin cancer tutorial
def make_model(
    num_classes: int = 2, is_plan=False, model_id="skin-cancer-model-encrypted"
):
    super_class = sy.Plan if is_plan else th.nn.Module

    class Net(super_class):
        """Similar to LeNet5 but without pooling."""

        def __init__(self):
            if is_plan:
                super(Net, self).__init__(id=model_id)
            else:
                super(Net, self).__init__()
            self.conv1 = th.nn.Conv2d(3, 6, 5, 1)
            self.conv2 = th.nn.Conv2d(6, 16, 5, 1)
            self.fc1 = th.nn.Linear(9216, 120)
            self.fc2 = th.nn.Linear(120, 84)
            self.fc3 = th.nn.Linear(84, num_classes)

            if is_plan:
                self.add_to_state(["conv1", "conv2", "fc1", "fc2", "fc3"])

        def forward(self, x):
            x = F.relu(self.conv1(x))
            x = F.relu(self.conv2(x))
            x = x.view(-1, 9216)
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.fc3(x)
            return x

    return Net()

# Upload encrypted model to worker anne and bob using james as the crypto provider
model.encrypt([bob, anne], crypto_provider=james)
bob.serve_model("skin-cancer", model, allow_download=True, allow_remote_inference=False)

#####

# Split dataset and tag them - used the Spam Notebook
```

[Anne Index after tag and model send](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_index.png)
[Bob index after tag](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/bob_index.png)
[Anne - Models](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/models_anne.png)
[Bob - Models](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/models_bob.png)
[Anne - Model Copy Allowed](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_is_model_copy_allowed.png)
[Anne - Model Copy Not Allowed](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_is_model_copy_allowed_not_allowed.png)
[Anne - Model Copy - Model Not Found](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_is_model_copy_allowed_not_found.png)
[Anne - Get Model - Not Allowed](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_get_model_not_allowed.png)
[Anne - Get Model - Not Found](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_get_model_not_found.png)
[Anne - Get Model - Success](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_get_model_success.png)
[Anne - Search Enc Model - Model Not Found](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_search_enc_model_not_found.png)
[Anne - Search Enc Model - Payload not correct](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_search_enc_model_payload_err.png)
[Anne - Search Dataset Tag - Success/Fail](http://swarm.cs.pub.ro/~gmuraru/OpenMined/Grid/anne_search_dataset_tag.png)

### CODE REVIEW

**Comment by gmuraru** [comment]
Still working on this one, will finish it this week, sorry for the looong delay.

**Comment by IonesioJunior** [comment]
No problem! You're doing a great work :)

**Comment by iamtrask** [comment]
Is this project still active?

**Comment by gmuraru** [comment]
I have something done for this but it is not finished :( @

**Comment by gmuraru** [comment]
I think it can be closed. @IonesioJunior ^^?

**Comment by IonesioJunior** [comment]
Yep! We still need the API documentation, but at this moment a lot of things will change. So, we can close this PR and open a new one in the future.

**Pull request closed without merging**
