### PR TITLE
add request id for identification

### LINKED ISSUE #685: Model-centric websockets to support concurrent requests
## What?
Ensure that model-centric websockets API is capable to support multiple concurrent requests using a single connection so that the client can distinguish which response is related to which request.

## How long?
Ideally we have unit test that checks that.

## Is your research related to a problem?
See
https://github.com/OpenMined/KotlinSyft/issues/235
https://github.com/OpenMined/SwiftSyft/issues/170

### PR DESCRIPTION
**Pull request by vkkhare**
## Description
implements request id for each socket request for identification and binning at workers. Closes #685 

## Affected Dependencies
fl_controller, fl_events

## How has this been tested?
- tests
- notebook deployment

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Review by hericlesme — APPROVED** [review]
LGTM

**Review by vvmnnnkv — COMMENTED** [review]
There can be error returned at some earlier stage of request processing (e.g. when 'type' is incorrect), it would be good to add request_id in that error too.
In general, if we could move echoing of request_id somewhere in common websocket request processing code, so it automatically adds in all websocket responses, that would be ideal :)

**Comment by vvmnnnkv** [comment]
Oh, also I think we can make it optional? E.g. pysyft client is sync and doesn't need this?

**Comment by cereallarceny** [comment]
@vkkhare DId you also do HTTP or just WS with this change? We need both.

**Pull request merged**
