### PR TITLE
Fl report endpoint

### LINKED ISSUE #468: Report FL Process
## Report

**HTTP endpoint**: `POST /federated/report`
**Socket type**: `federated/report`
**Request data**:
```json
{
  "worker_id": "ID OF THE WORKER",
  "request_key": "LONG HASH VALUE",
  "diff": "FINAL MODEL DIFF FROM TRAINING"
}
```

This method will allow a worker that has been accepted into a cycle and finished training a model on their device to upload the resulting model diff.

If the worker did not train a protocol to be done after the plan(s) was executed, then they will simply submit their entire model diff. If they want to manually add noise to this diff as a layer of protection, they may do so at the developer's discretion from inside the worker implementation.

If the worker did execute a protocol and they have finished the secure aggregation protocol with other workers, they will now receive a share of the resulting securely aggregated model diff. In this case, they will submit the share of the diff, rather than their original model diff. PyGrid will handle the decryption of the shares once they're all submitted.

Response: `{ "status": "success" }`

The response of success is sent if the response is a 200. **The worker should not be informed if the model diff was accepted or denied as part of the global model update.**

Refers to #445

### PR DESCRIPTION
**Pull request by Prtfw**
# Pull Request Template

## Description

allows a worker to report model diff via endpoint /federated/report
(only accepts a report, averaging will be in a subsequent pr)
 
(I'm websockets #newb... not sure if things are done correctly but seems to be working)

Fixes #468 

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- test a: send bad json => get invalid json msg
- test b: send good json but bad data => get err msg
https://share.getcloudapp.com/jkuKyXZ6
- test c: send fake api call and proper json => get success 
https://share.getcloudapp.com/7KuRx6m0

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by joaolcaas** [comment]
Hey @Prtfw , i'm a newb in websockets as well, but when i was wondering about this issue, i thought  the websocket routes would be at this [file](https://github.com/OpenMined/PyGrid/blob/dev/gateway/app/main/events/__init__.py). Just saying this to give you a quick update, i thing the other guys can talk this a lot better.

**Comment by Prtfw** [comment]
> Hey @Prtfw , i'm a newb in websockets as well, but when i was wondering about this issue, I thought the websocket routes would be at this [file](https://github.com/OpenMined/PyGrid/blob/dev/gateway/app/main/events/__init__.py) (but I'm not sure). Just saying this to give you a quick update, i thing the other guys can talk this a lot better.

haha yeah @joaolcaas! lets learn this stuff together... I think gateway/app/main/events/__init__.py is a very reasonable place to put this... I will give it a few more hours to see if anyone else has instructions on where this should go : ) Thanks lots for reviewing!

**Comment by joaolcaas** [comment]
> haha yeah @joaolcaas! lets learn this stuff together... I think gateway/app/main/events/**init**.py is a very reasonable place to put this... I will give it a few more hours to see if anyone else has instructions on where this should go : ) Thanks lots for reviewing!

Sure, let's do it! You are welcome!

**Comment by IonesioJunior** [comment]
Hello @Prtfw , @joaolcaas,

Yeah, You're right! We define all the WS events at `events/__init__.py`.
https://github.com/OpenMined/PyGrid/blob/c44e9b4dc970f4f0be0e3df16056af458df4407b/gateway/app/main/events/__init__.py#L18-L26
This is basically all the events (websocket endpoints) that we have right now. If we want to add a new endpoint, we just need to create a new function and add a new key (route) to this dictionary.

Actually, the `events.fl_events.report` already works as a websocket endpoint for `report` websocket requests.

**Also, I really enjoyed the code reuse in the HTTP method. This allows us to guarantee the same behavior in HTTP/WS requests and to avoid code repetition and collateral effects. We can use the same approach at other endpoints.**

 I'm very happy to see our progress! 🚀

**Comment by IonesioJunior** [comment]
@Prtfw , do you want to add anything else to this PR?

**Comment by Prtfw** [comment]
@IonesioJunior nope... I see you just approved (and also fixed my test failure) so I will squash n merge
also a thank you to @joaolcaas for the comments / feedback.

**Pull request merged**
