### PR TITLE
[WIP] Add Local Encrypted Linear Regression notebook

### LINKED ISSUE #373: [Notebook] Encrypted Linear Regression
Reproduce [Encrypted Linear Regression](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Encrypted%20Linear%20Regression.ipynb) notebook.

**Acceptance criteria:**
- Keep the author's name and add your name.
- Perform Encrypted Linear Regression using PyGrid Nodes.

### PR DESCRIPTION
**Pull request by Benardi**
# Add Local Encrypted Linear Regression notebook using Grid Workers.

## Description

Add [Encrypted Linear Regression](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/advanced/Encrypted%20Linear%20Regression.ipynb), and replace Virtual Workers for Grid Workers

Fixes #373 

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Execute the same result related code as in the original notebook

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by iamtrask** [comment]
Where are we on this guy?

**Comment by Benardi** [comment]
At the time, the application ended up stuck in what seemed like a deadlock when Virtual Workers were replaced for grid.WebsocketClientWorker. The issue/pull request was blocked by something else, as it was not part of this issue/PR to solve this unforeseen deadlock. 
I reported this, but at the time had no credentials to tag this pull request as blocked.

**Comment by Benardi** [comment]
This issue most likely should be moved to PySyft.

**Comment by IonesioJunior** [comment]
For now, I think we can close this PR, but I believe that in the short and medium term, work on it again.

**Pull request closed without merging**
