### PR TITLE
Add hindi translations

### PR DESCRIPTION
**Pull request by UtkarshChaurasia**
# Pull Request Template

## Description

Addition of Hindi translations of example notebooks.

Issue: #558

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by jmaunon** [comment]
Nice PR
However the original English version should be updated before. A reader cannot follow the instructions

**Comment by UtkarshChaurasia** [comment]
@jmaunon So should I wait for the updation of the English version?

**Comment by jmaunon** [comment]
If you want, a new PR just for updating the tutorial would be nice.
In slack there are problems regarding this (now there are no websocket folder, for example) and generates misunderstanding

**Comment by jmaunon** [comment]
Actually, there is an issue about this https://github.com/OpenMined/PyGrid/issues/564

**Comment by UtkarshChaurasia** [comment]
Thanks for info I'll look into to problem and will create a PR for updating the tutorial.

**Comment by UtkarshChaurasia** [comment]
I see that examples notebook got updated so should I update their Hindi translations in order to make this PR merge?

**Pull request closed without merging**
