### PR TITLE
Updated k8s Readme 

### LINKED ISSUE #408: Create Kubernetes config file
**Is your feature request related to a problem? Please describe.**
We want to provide container orchestration to automate the deployment, sizing, and management to PyGrid node containers.

**Describe the solution you'd like**
We want to provide scaling up/down, health check and fault tolerance to our platform using Kubernetes.

### PR DESCRIPTION
**Pull request by gantir**
## Description

The readme file for installing k8s hasn't been updated with proper Docker image name. Updating the same.

Fixes #408 

## Type of change

Please mark options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
This is a documentation change.

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by hericlesme** [comment]
@gantir I believe that if the user already has the images from our repository and wants to build their own they will have the same name. Of course, the Docker Hub image has the `latest` tag. But don't you think it gets a little confusing?

**Comment by hericlesme** [comment]
It's just a specific situation. What do you think about it?

**Comment by gantir** [comment]
@hericlesme ,
I see the point you are making. However the instructions also has to be in sync with what we have in docker-compose. When someone want's to built the image locally and just use docker compose, it should work. 
The way docker works if an image exists in local image cache it just uses the same, so in this case things continue to work as default behaviour. Users can make specific changes if they wish to deviate.

**Comment by gantir** [comment]
@hericlesme ,
There are two ways I can think of:

1. Default behaviour where a local docker build overrides remote cache. (What I currently suggested). Inform the users of the same.
2. Update the instructions and explicitly point that this image is different from remote, they will need to update docker-compose, k8s incase they want to use the local image.

My personal preference is for 1. But am ok with 2 if that will be more representative for the community of users.

**Comment by hericlesme** [comment]
@gantir, now I understand your point. We can proceed with what you're suggesting.
But, just one more thing. In the docker-compose we pull a specific tag of the image, `<image>:latest`, but these instructions don't build the image without a tag. If I'm not mistaken, the docker-compose will not catch the custom image, but the docker hub image.

What do you suggest about it? We can just notify the user to update the docker-compose, or override the image with the latest tag.

**Comment by gantir** [comment]
@hericlesme ,

Right. 

Docker has a weird meaning for latest. Look at this article for [explanation](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375).

In my mind nothing changes from the documentation perspective. The following is how I think it should work:

- In local, just follow the commands as already given. And since we don't specify any tag docker treats the latest untagged build as latest.
- When we push an image to openmined repository on dockerhub, explicitly ensure that we version it and also assign the latest tag.

I am working as per your suggestion on having a dockerhub hook in issue #419  and will take care of this.

Am I missing something?

**Comment by hericlesme** [comment]
@gantir, no, you don't. Thank you for the changes! ❤️

**Pull request merged**
