### PR TITLE
Auto formatting

### PR DESCRIPTION
**Pull request by AmrMKayid**
## Description
I created a `core` submodule which contains the generic files (`codes.py` and `exceptions.py`) and should be extended in the future to include any abstract classes or core files used in the library.

### Formatting & Code Style Organization
- [x] Using [yapf](https://github.com/google/yapf) for modules formatting
- [ ] Using [isort](https://pypi.org/project/isort/) for automatically sorting the imports
- [x] Using [docformatter](https://pypi.org/project/docformatter/) to automatically formats docstrings.
- [x] edited `Makefile` by adding new rule `format` for organizing the code locally
- [x] edited `.pre-commit-config.yaml` for running yapf and sort on commits.

## Affected Dependencies
Installing yapf, sort, and docformatter

## How has this been tested?
- Provide instructions so we can reproduce.
> Yapf can be integrated in your favorite text editor and you can enable format on save while developing your code.
- Sublime Text (using PyYapf):
  ```JSON
  {
      "on_save": true,
      "config": {
          "based_on_style": "pep8",
          "INDENT_WIDTH": 4,
          "COLUMN_LIMIT": 80,
      },
  }
  ```
- VSCode:
  ```
  {
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: pep8, indent_width: 4, column_limit: 80}"
    ],
  }
  ```
- Command line:
  ```
  yapf --verbose --in-place --recursive --style='{based_on_style: pep8, indent_width:4, column_limit:80}' -i <file>
  ```

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by AmrMKayid** [comment]
I just noticed that there is already a python formatted which is `black` ... should I revert back from using yapf and instead integrate `black` for automatic formatting ?!

**Comment by IonesioJunior** [comment]
I vote for `black` maintenance. Just to preserve a certain level of standardization in OM python repositories, since most of them use black for python formatting.

**Comment by cereallarceny** [comment]
Yes @AmrMKayid , you should use black. It’s also used in PySyft. Revert the PR to use it instead of the other library.

**Comment by AmrMKayid** [comment]
Awesome! thanks for informing me ... just revert to black formatting now

**Comment by hericlesme** [comment]
Will we update the lint stage in the GitHub Actions workflow file?

**Comment by IonesioJunior** [comment]
https://github.com/psf/black/issues/127
https://github.com/timothycrosley/isort/issues/694

Apparently `isort `is incompatible with `black`. This explains the errors we were having when checking code style/format.

**Comment by timothycrosley** [comment]
@IonesioJunior isort is fully compatible with black, you just need to use the included `black` profile and compatibility is guaranteed: https://timothycrosley.github.io/isort/docs/configuration/profiles/. The issue you pointed to is just a "Lets keep communication open in case any incompatibilities appear" catch all issue.

**Pull request merged**
