### PR TITLE
Connection speed test

### PR DESCRIPTION
**Pull request by IonesioJunior**
## Description

Add connection speed test routes

Fixes # (#502 )

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [x] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by IonesioJunior** [comment]
Could you guys give me a brief review?

**Comment by cereallarceny** [comment]
Hey @Ionesio, it doesn’t look like this PR does anything except create two functions.  Did you add the random file generator?  Please read the specification again, I think it should clear things up! 😊

**Comment by IonesioJunior** [comment]
@cereallarceny 
This was just the initial commit to sketching the endpoints.
I would like to ask some questions first. 😃 

Do we already have a defined file size?
What should be the mime-type?

**Comment by cereallarceny** [comment]
Good question!  I think the file size should be something fairly large: 64mb? That'd give a pretty good idea about bandwidth I think - far more than something smaller. Mime-type... text/plain? I don't think it matters since the file is just non-sense. Since @vvmnnnkv, @mjjimenez, and @vkkhare have to write the upload function (with random file generation) themselves on their platforms, I'm gonna bring them into this conversation as well.

**Pull request merged**
