### PR TITLE
[WIP] Docker build grid-gateway, grid-node

### LINKED ISSUE #417: Automated docker builds
**Is your feature request related to a problem? Please describe.**
The docker images of PyGrid nodes and Gateway are built locally only. Having images in remote repositories (such as Docker Hub, or GitHub Package) can be helpful. The image could just be pulled, either using Docker locally or for example in a Kubernetes deployment.

**Describe the solution you'd like**
PyGrid could have automated builds that automatically push images to remote repositories.

**Additional context**
#415

### PR DESCRIPTION
**Pull request by gantir**
## Description

Automated docker build for pysyft-grid-gateway, pysyft-grid-node to docker hub.

Fixes #417 

## Type of change
Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This PR builds and pushes to docker hub the docker image for gateway, node. 

The pysyft-grid-gateway image is built and uplodaed to dockerhub. 
The pysyft-grid-node image has an error while building.

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by gantir** [comment]
@hericlesme ,
Have put in condition that the docker build is triggered only on push to dev. Assuming the appropriate username and password are stored in secret on travis it will push to dockerhub.

**Comment by hericlesme** [comment]
@gantir I think docker builds can be triggered in docker hub using webhooks.

*"Docker Hub can automatically build images from source code in an external repository and automatically push the built image to your Docker repositories."*

You can see more about automated builds [here](https://docs.docker.com/docker-hub/builds/).

Anyway, yes, using Travis could be an alternative.  Now, we just need someone with the needed privileges in our Docker Hub Organization.

**Comment by hericlesme** [comment]
By the way, you're doing a great job, thank you! :D

**Comment by gantir** [comment]
@hericlesme,
Ah didn't know about the docker hub thing. Even otherwise the travis.yml is now refactored to use build stages ;).

Thanks for the good words. !!

**Comment by IonesioJunior** [comment]
I'm so sorry for the delay.
We've finally published our official images at docker hub ( [grid-node](https://hub.docker.com/repository/docker/openmined/grid-node) / [grid-gateway](https://hub.docker.com/repository/docker/openmined/grid-gateway) )

**Comment by IonesioJunior** [comment]
Hello @gantir!
It would be awesome if we can update our docker images when changes are applied to PySyft's repository too.
It would help to keep the compatibility between the platform and the library. :)

**Comment by gantir** [comment]
@IonesioJunior,

The best way for what you are asking is to do what was suggested by @hericlesme . If you can add my docker user to openmined organization, I can create the appropriate webhooks.

Pinged you on slack with my docker user id.

Essentially we need to do the following :
[ ] openmined/grid-gateway on pysyft update
[ ] openmined/grid-gateway on syft-proto update
[ ] openmined/grid-gateway on pygrid update
[ ] openmined/grid-node on pysyft update
[ ] openmined/grid-node on syft-proto update
[ ] openmined/grid-node on pygrid update

**Comment by hericlesme** [comment]
We migrated from Travis CI to GitHub Actions. As such, these changes no longer apply to our context. Thank you, @gantir. :wink:

**Pull request closed without merging**
