### PR TITLE
Kubernetes Config file

### LINKED ISSUE #408: Create Kubernetes config file
**Is your feature request related to a problem? Please describe.**
We want to provide container orchestration to automate the deployment, sizing, and management to PyGrid node containers.

**Describe the solution you'd like**
We want to provide scaling up/down, health check and fault tolerance to our platform using Kubernetes.

### PR DESCRIPTION
**Pull request by gantir**
## Description

Provided k8s config for node and gateway

Fixes #408 

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
- [ ] New Unit tests added
- [ ] Unit tests pass locally with my changes

### CODE REVIEW

**Comment by gantir** [comment]
@IonesioJunior,
Most of the things are now in place. I am having one major issue which is the docker image. I could not build the node image locally, so have referenced my personal docker for the same.

I don't see any automated build which pushes the images to docker. May be we can have one more issue which can push the docker image to docker hub?

**Comment by hericlesme** [comment]
@gantir, @IonesioJunior, I think that's good to have an automated build in the docker hub, or maybe in the GitHub package registry...

**Comment by hericlesme** [comment]
I created a feature request for automated builds. #417. Once resolved, does that remove your impediment, @gantir?

**Comment by gantir** [comment]
@hericlesme,

Thanks, it's not an impediment but yes we cannot use it outside of local cluster.

Once we have builds on docker then this can work on any cluster.

Do you know if there is a docker hub account. I already have enough stuff to fix #417

**Comment by gantir** [comment]
The following is what is included:

- [x] Gateway deployment and service
- [x] App (Node) deployment and service
- [x] Configurability using Kustomize to templatize the base configurations.
- [x] Overlays for local, test & prod deployments
- [x] Deploy script to deploy local and remote clusters
- [x] Tested on local (minikube), remote (GKE)

Points to note:
* Currently the services are exposed as LoadBalancer. Depending on final usecase more work needs to be done if need to expose as Ingress
* Currently pulling the docker image from my personal dockerhub.

Look forward to review comments.

**Comment by gantir** [comment]
@IonesioJunior ,

From your comment on slack, I gather there is a docker hub organisational account. Once the images are pushed to the same, I will update the (grid gateway, grid node) deployments to refer to that image.

**Comment by hericlesme** [comment]
@gantir We already have the docker images at docker hub. https://github.com/OpenMined/PyGrid/pull/419#issuecomment-566321376 :nerd_face:

**Comment by gantir** [comment]
@IonesioJunior ,
Can you review this PR. I have updated it with the images from docker. Check the list of features added in an earlier comment of mine.

**Pull request merged**
